<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerP5u0FxF\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerP5u0FxF/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerP5u0FxF.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerP5u0FxF\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerP5u0FxF\App_KernelDevDebugContainer([
    'container.build_hash' => 'P5u0FxF',
    'container.build_id' => 'b8957e37',
    'container.build_time' => 1753858520,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerP5u0FxF');
