<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4TYDNw8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4TYDNw8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4TYDNw8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4TYDNw8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container4TYDNw8\App_KernelDevDebugContainer([
    'container.build_hash' => '4TYDNw8',
    'container.build_id' => '86cf2b49',
    'container.build_time' => 1753787296,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container4TYDNw8');
