<?php

namespace Container4TYDNw8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPermissionServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\PermissionService' shared autowired service.
     *
     * @return \App\Service\PermissionService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Service/PermissionService.php';

        return $container->privates['App\\Service\\PermissionService'] = new \App\Service\PermissionService(($container->privates['App\\Repository\\UserRoleRepository'] ?? $container->load('getUserRoleRepositoryService')), ($container->privates['App\\Repository\\ModuleRepository'] ?? $container->load('getModuleRepositoryService')));
    }
}
